FROM python:3.9
ENV PYTHONUNBUFFERED=1

RUN mkdir /app
RUN mkdir /app/logs
WORKDIR /app

COPY . .
RUN chmod +x script.sh
RUN ./script.sh
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install gunicorn

CMD ["gunicorn", "--bind", "0:8000", "config.wsgi:application"]
