# Generated by Django 4.0.3 on 2022-06-04 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Bookmark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, help_text='구매일시', null=True)),
            ],
            options={
                'db_table': 'Buy',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'Tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('state', models.IntegerField(help_text='양도권 상태 (0: 판매중, 1: 예약중, 2: 판매완료)')),
                ('tag_hash', models.BigIntegerField()),
                ('is_membership', models.BooleanField()),
                ('is_holding', models.BooleanField()),
                ('remaining_number', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField()),
                ('can_nego', models.BooleanField()),
                ('trade_type', models.IntegerField()),
                ('has_shower', models.BooleanField()),
                ('has_locker', models.BooleanField()),
                ('has_clothes', models.BooleanField()),
                ('has_gx', models.BooleanField()),
                ('can_resell', models.BooleanField()),
                ('can_refund', models.BooleanField()),
                ('description', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=255)),
                ('transfer_fee', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('main_image', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Ticket',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('is_main', models.BooleanField()),
                ('thumbnail_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TicketImage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'TicketTag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.OneToOneField(db_column='id', help_text='User ID(integer)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='app_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
