# Generated by Django 4.0.3 on 2022-05-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Buy',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserTag',
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
    ]
