# Generated by Django 4.0.3 on 2022-05-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialuser',
            old_name='social_id',
            new_name='uid',
        ),
    ]
