FROM python:3.9
ENV PYTHONUNBUFFERED=1

RUN mkdir /app
RUN mkdir /app/logs
WORKDIR /app

COPY . .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install gunicorn

CMD ["gunicorn", "--bind", "0:8080", "config.wsgi:application"]
